title: Beauflix Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.beauflix.net
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: Primary Datacenter
    - name: Media Services
      description: ""
      category: Primary Datacenter
      link: https://example.com/
    - name: Storage
      description: ""
      category: Primary Datacenter
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#f44d2d"
  enableLastMod: true
  headerTextColor: white
  logo: /img/beauflix.png
  incidentPostsPerPage: 3
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Primary Datacenter
      description: The main servers are located here.
      closed: false
    - name: Uncategorized
      untitled: true
  description: No guarantees, baby
  enableCustomHTML: true
  useLargeHeaderDesign: false
